FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @fedjobs/api build

EXPOSE 3001
CMD ["pnpm", "--filter", "@fedjobs/api", "start"]